apiVersion: v2
name: auth-service
description: Auth and OAuth2 microservice
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: microservice
    version: "0.1.0"
    repository: "file://../../helm/charts/microservice"
