controller:
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  ingressClass: nginx
  service:
    type: NodePort
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  metrics:
    enabled: true
