controller:
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  ingressClass: nginx
  service:
    type: LoadBalancer
  replicaCount: 3
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 1Gi
  metrics:
    enabled: true
  config:
    use-forwarded-headers: "true"
    ssl-redirect: "true"
    hsts: "true"
    hsts-max-age: "31536000"
    hsts-include-subdomains: "true"
